BEGIN;

INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('What''s Wrong With The World, Mama?', now() - '10 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('Sharks Are Friends, Not Food', now() - '6 days'::INTERVAL, null),
    ('Defender Of The Curse', now() - '6 days'::INTERVAL, null),
    ('Drinking At The Ocean', now() - '6 days'::INTERVAL, null),
    ('Man And My Journey', now() - '6 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('Horse And Pig', now() - '6 days'::INTERVAL, null),
    ('Frightened Of The Intruders', now() - '4 days'::INTERVAL, null),
    ('I Will Tell You The Truth About Cats In The Next 60 Seconds', now() - '4 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('Lorem ipsum dolor sit amet, consectetur', now() - '4 days'::INTERVAL, null),
    ('How To Learn About Dogs In Only 10 Days', now() - '4 days'::INTERVAL, null),
    ('Here''s What Industry Insiders Say About Dogs', now() - '4 days'::INTERVAL, null),
    ('10 Artist That Had Gone Way Too Far', now() - '4 days'::INTERVAL, null),
    ('Seven Principles That You Can Learn From Artist', now() - '4 days'::INTERVAL, null),
    ('5 Stereotypes About Music That Aren''t Always True', now() - '2 days'::INTERVAL, null),
    ('Understand The Background Of Music Now', now() - '2 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('Quiz: How Much Do You Know about Music?', now() - '2 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('What Is STAR WARS and How Does It Work?', now() - '2 days'::INTERVAL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('Why I Hate STAR WARS', now(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('STAR WARS Iphone Apps', now(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.'),
    ('STAR WARS: An Incredibly Easy Method That Works For All', now(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam blandit facilisis leo, id condimentum nulla. Maecenas eu est hendrerit, viverra justo quis, hendrerit orci. Suspendisse et faucibus massa. In nec accumsan justo. Aliquam mattis, nisl vitae placerat tincidunt, eros erat mattis lacus, ac elementum elit ligula vel turpis. Integer ac tellus nec enim congue scelerisque et eu leo. Nam quis ante blandit, rhoncus diam vel, lacinia urna. Vestibulum sodales pellentesque placerat.');

COMMIT;